// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsStreaming() {
  return window['go']['main']['App']['IsStreaming']();
}

export function StartStream() {
  return window['go']['main']['App']['StartStream']();
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}
